
CREATE TABLE `operator` (
    `id` int NOT NULL AUTO_INCREMENT,
    `full_name` varchar(255) DEFAULT NULL,
     PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
